<?php

declare(strict_types=1);

return [
    'organization' => [
        'organization_name' => 'POSITIVE TREE FOUNDATION',
        'tagline' => 'EVERY LEAF HAS A DREAM',
        'address_lines' => [
            'Plot No. 54, Sri Kanchi Nagar, Extension II Chinnaiyankulam, Orikkai, Kancheepuram, Kanchipuram – 631502, Tamil Nadu.',
        ],
        'phone' => '+91 6384184900',
        'email' => 'info@positivetree.ngo',
        'website' => 'https://positivetree.ngo',
        'logo_filename' => 'logo.png',
    ],
    'receipt' => [
        'title' => 'DONATION RECEIPT',
        'footer_text' => 'Thank you for supporting Positive Tree Foundation. This receipt acknowledges your generous contribution towards our social impact initiatives.',
        'banner_text' => 'Thank you for helping us grow hope, care, and opportunity.',
        'signature_name' => 'Authorized Signatory',
        'signature_title' => 'Positive Tree Foundation',
        'signature_filename' => null,
        'accent_color' => '#20994D',
        'brand_brown' => '#986326',
        'show_fields' => [
            'email' => true,
            'phone' => true,
            'cause' => true,
            'channel' => true,
            'payment_method' => true,
            'transaction_ref' => true,
            'amount_words' => true,
            'payment_status' => true,
            'donated_at' => true,
            'notes' => false,
        ],
        'print' => [
            'paper' => 'A4',
            'orientation' => 'portrait',
            'margin_top_mm' => 0,
            'margin_right_mm' => 0,
            'margin_bottom_mm' => 0,
            'margin_left_mm' => 0,
        ],
    ],
    'certificate' => [
        'title' => 'DONATION CERTIFICATE',
        'opening_text' => 'This is to certify that',
        'body_text' => 'has generously contributed {{amount_inr}} ({{amount_words}}) towards {{cause}} at Positive Tree Foundation.',
        'closing_text' => 'This certificate is issued in gratitude for your generous support towards our mission. The contribution details have been verified by our Accounts Team.',
        'eighty_g_registration_number' => '',
        'eighty_g_notes' => [
            'Eligible for deduction under Section 80G of the Income Tax Act, 1961.',
            'Deduction available to the donor subject to valid registration, donor eligibility, mode of payment, and prevailing law.',
        ],
        'signatory_name' => 'Authorized Signatory',
        'signatory_title' => 'Accounts Team',
        'signatory_label' => 'Authorized Signatory',
        'accent_color' => '#1B4332',
        'brand_brown' => '#986326',
        'show_fields' => [
            'receipt_number' => true,
            'certificate_number' => true,
            'cause' => true,
            'donated_at' => true,
            'channel' => true,
            'payment_method' => true,
            'donor_pan' => true,
            'amount_words' => true,
        ],
        'print' => [
            'paper' => 'A4',
            'orientation' => 'portrait',
            'margin_top_mm' => 0,
            'margin_right_mm' => 0,
            'margin_bottom_mm' => 0,
            'margin_left_mm' => 0,
        ],
    ],
];
